language: cpp
compiler: gcc
os: linux
dist: xenial

before_install:
  - sudo apt-get install build-essential libssl-dev libboost-all-dev libqrencode-dev libminiupnpc-dev -y
  - sudo apt-get install qtcreator qttools5-dev-tools  libqt5webkit5-dev -y

  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update
  - sudo apt-get install libdb4.8-dev libdb4.8++-dev -y
  
script:
  - cd src ; RELEASE=1 STATIC=TRUE make -j2 -f makefile.unix ; strip okcashd